services: docker
dist: trusty
language: cpp
env:
  global:
  - DO_BUILD=yes
  - DO_TEST=yes
  - GTEST_COLOR=1
matrix:
  include:
  - compiler: gcc7
    env:
    - COMPILER=g++
    - IMG=gcc-7
    - CMAKE_EXTRA_FLAGS="-DENABLE_CUDA=Off"

script:
- docker run --rm --user='root' -v ${TRAVIS_BUILD_DIR}:/home/axom axom/compilers:$IMG chown -R axom /home/axom
- docker run --rm  -v ${TRAVIS_BUILD_DIR}:/home/axom -e COMPILER -e DO_BUILD -e DO_TEST -e DO_MEMCHECK -e CMAKE_EXTRA_FLAGS -e GTEST_COLOR axom/compilers:$IMG ./source/scripts/travis/build_and_test_umpire.sh
